project:
  type: website
  output-dir: _book
  preview:
    port: 4200
    browser: false
    host: 0.0.0.0

website:
  sidebar:
    style: "docked"
    search: true
    contents: 
    - section: "Intro"
      contents: 
        - doc/01-Introducao/01-intro.qmd
        - doc/01-Introducao/02-Logica_de_programacao.qmd

# book:
#   title: "Lpi"
#   author: "Norah Jones"
#   date: "07/03/2024"
#   chapters:
#     - index.qmd
    # - doc/01-Introducao/
    # - doc/01-Introducao/01-intro.qmd
    # - doc/01-Introducao/02-Logica_de_programacao.qmd
    # - doc/01-Introducao/03-Algoritmo.qmd
    # - doc/01-Introducao/04-Linguagem_de_programacao.qmd
    # - doc/02-Basicos/02-Entrada_saida.qmd
    # - summary.qmd
    # - references.qmd
  # - index.qmd
  

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



