project:
  type: book
  output-dir: _book
  preview:
    port: 4200
    browser: false
    host: 0.0.0.0



book:
  title: "Linguagem de Programação"
  author: "Darlon Vasata"
  # date: "03/07/2024"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Introdução"
      chapters:
        - doc/01-Introducao/00-teste.qmd

  

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



