version: '3'
services:
  #Materiais
  init:
    image: node:19-slim
    container_name: materiais_init
    profiles: [ 'init', 'all' ]
    volumes:
      - ./:/src
    working_dir: /src
    command: npm install

  materiais:
    image: node:19-slim
    container_name: materiais
    #profiles: ['run', 'redes', 'all']
    volumes:
      - ./:/src
    ports:
      - "3001:3000"
    working_dir: /src
    command: npx docusaurus start --host 0.0.0.0
    restart: always

  deploy:
    image: node:19
    container_name: materiais_deploy
    profiles: [ 'deploy', 'all' ]
    environment:
      - GIT_USER=$GIT_USER
      - GIT_PASS=$GIT_PASS
      - GIT_NAME=$GIT_NAME
      - GIT_MAIL=$GIT_MAIL
      - USE_SSH=$USE_SSH
      - CURRENT_BRANCH=$CURRENT_BRANCH
    volumes:
      - ./:/src
    working_dir: /src
    command: bash -c "git config --global user.email $GIT_MAIL && git config --global user.name $GIT_NAME && yarn deploy"
  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer
  #   profiles: ['monitor']
  #   ports:
  #     - 9000:9000
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./portainer:/data 
