version: '3'
services:
  #REDES
  redes_init:
    image: node:19-slim
    container_name: redes_init
    profiles: ['init', 'redes', 'all']
    volumes:
      - ./redes:/redes
    working_dir: /redes
    command: npm install

  redes:
    image: node:19-slim
    container_name: redes
    profiles: ['run', 'redes', 'all']
    volumes:
      - ./redes:/redes
    ports:
      - "3001:3000"
    working_dir: /redes
    command: npx docusaurus start --host 0.0.0.0
    #restart: always
    
  redes_deploy:
    image: node:19
    container_name: redes_deploy
    profiles: ['deploy', 'redes', 'all']
    environment:
      - GIT_USER=$GIT_USER
      - GIT_PASS=$GIT_PASS
      - GIT_NAME=$GIT_NAME
      - GIT_MAIL=$GIT_MAIL
      - USE_SSH=$USE_SSH
      - CURRENT_BRANCH=$CURRENT_BRANCH
    volumes:
      - ./redes:/redes
    working_dir: /redes
    command: bash -c "git config --global user.email $GIT_MAIL && git config --global user.name $GIT_NAME && yarn deploy"
    
  #ALGORITMOS
  algoritmos_init:
    image: node:19-slim
    container_name: algoritmos_init
    profiles: ['init', 'algoritmos', 'all']
    volumes:
      - ./algoritmos:/algoritmos
    working_dir: /algoritmos
    command: bash -c "npm install && npm install --save remark-math@3 rehype-katex@5 hast-util-is-element@1.1.0"

  algoritmos:
    image: node:19-slim
    container_name: algoritmos
    profiles: ['run', 'algoritmos', 'all']
    volumes:
      - ./algoritmos:/algoritmos
    ports:
      - "3000:3000"
    working_dir: /algoritmos
    command: npx docusaurus start --host 0.0.0.0
    #restart: always
    
  algoritmos_deploy:
    image: node:19
    container_name: algoritmos_deploy
    profiles: ['deploy', 'algoritmos', 'all']
    environment:
      - GIT_USER=$GIT_USER
      - GIT_PASS=$GIT_PASS
      - GIT_NAME=$GIT_NAME
      - GIT_MAIL=$GIT_MAIL
      - USE_SSH=$USE_SSH
      - CURRENT_BRANCH=$CURRENT_BRANCH
    volumes:
      - ./algoritmos:/algoritmos
    working_dir: /algoritmos
    command: bash -c "git config --global user.email $GIT_MAIL && git config --global user.name $GIT_NAME && yarn deploy"
    
    #Robotica
  robotica_init:
    image: node:19-slim
    container_name: robotica_init
    profiles: ['init', 'robotica', 'all']
    volumes:
      - ./robotica:/robotica
    working_dir: /robotica
    command: npm install

  robotica:
    image: node:19-slim
    profiles: ['run', 'robotica', 'all']
    container_name: robotica
    volumes:
      - ./robotica:/robotica
    ports:
      - "3030:3000"
    working_dir: /robotica
    command: npx docusaurus start --host 0.0.0.0
    
  robotica_deploy:
    image: node:19
    container_name: robotica_deploy
    profiles: ['deploy', 'robotica', 'all']
    environment:
      - GIT_USER=$GIT_USER
      - GIT_PASS=$GIT_PASS
      - GIT_NAME=$GIT_NAME
      - GIT_MAIL=$GIT_MAIL
      - USE_SSH=$USE_SSH
      - CURRENT_BRANCH=$CURRENT_BRANCH
    volumes:
      - ./robotica:/robotica
    working_dir: /robotica
    command: bash -c "git config --global user.email $GIT_MAIL && git config --global user.name $GIT_NAME && yarn deploy"
    
    #SO
  so_init:
    image: node:19-slim
    container_name: so_init
    profiles: ['init', 'so', 'all']
    volumes:
      - ./so:/so
    working_dir: /so
    command: bash -c "npm install && npm install --save remark-math@3 rehype-katex@5 hast-util-is-element@1.1.0"

  so:
    image: node:19-slim
    container_name: so
    profiles: ['run', 'so', 'all']
    volumes:
      - ./so:/so
    ports:
      - "3002:3000"
    working_dir: /so
    command: npx docusaurus start --host 0.0.0.0
    #restart: always
    
  so_deploy:
    image: node:19
    container_name: so_deploy
    profiles: ['deploy', 'so', 'all']
    environment:
      - GIT_USER=$GIT_USER
      - GIT_PASS=$GIT_PASS
      - GIT_NAME=$GIT_NAME
      - GIT_MAIL=$GIT_MAIL
      - USE_SSH=$USE_SSH
      - CURRENT_BRANCH=$CURRENT_BRANCH
    volumes:
      - ./so:/so
    working_dir: /so
    command: bash -c "git config --global user.email $GIT_MAIL && git config --global user.name $GIT_NAME && yarn deploy"

#PROBLEMAS
  problemas_init:
    image: node:19-slim
    container_name: problemas_init
    profiles: ['init', 'problemas', 'all']
    volumes:
      - ./problemas:/problemas
    working_dir: /problemas
    command: bash -c "npm install && npm install --save remark-math@3 rehype-katex@5 hast-util-is-element@1.1.0"

  problemas:
    image: node:19-slim
    container_name: problemas
    profiles: ['run', 'problemas', 'all']
    volumes:
      - ./problemas:/problemas
    ports:
      - "3010:3000"
    working_dir: /problemas
    command: npx docusaurus start --host 0.0.0.0
    #restart: always
    
  problemas_deploy:
    image: node:19
    container_name: problemas_deploy
    profiles: ['deploy', 'problemas', 'all']
    environment:
      - GIT_USER=$GIT_USER
      - GIT_PASS=$GIT_PASS
      - GIT_NAME=$GIT_NAME
      - GIT_MAIL=$GIT_MAIL
      - USE_SSH=$USE_SSH
      - CURRENT_BRANCH=$CURRENT_BRANCH
    volumes:
      - ./problemas:/problemas
    working_dir: /problemas
    command: bash -c "git config --global user.email $GIT_MAIL && git config --global user.name $GIT_NAME && yarn deploy"    
