# FROM analythium/r2u-quarto:20.04
FROM darlon/quarto-amd64
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt -y install tzdata
RUN apt -y install texlive-xetex
RUN apt -y install texlive-fonts-extra
RUN apt -y install texlive-fonts-recommended
RUN apt -y install lmodern

#Chrome on docker to compile mermaid on quarto
RUN apt-get update && apt-get install gnupg wget -y && wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && apt-get update && apt-get install google-chrome-stable -y --no-install-recommends && rm -rf /var/lib/apt/lists/*

# RUN  apt -y install texlive-latex-extra
# RUN  apt -y install texlive-latex-recommended

#Pdf com tinytex. problema: updates a cada uso
# RUN quarto install tool tinytex
# RUN quarto update tinytex
