# Linguagem de programação

Uma **linguagem de programação** é um conjunto de funções específicas e bem definidas, com as quais é possível desenvolver um **algoritmo**.

Chamamos de **código** a um algoritmo desenvolvido em uma linguagem de programação.

**Atividade**  

- Um homem precisa atravessar um rio com um barco que possui capacidade de transportar apenas ele mesmo e mais uma de suas três cargas, que são: um lobo, um bode e uma caixa de alfafa. Indique as ações necessárias para que o homem consiga atravessar o rio sem perder suas cargas. Algumas regras devem ser sempre respeitadas: o lobo não pode ficar sozinho com o bode e o bode não pode ficar sozinho com a alfafa.  
    - Desenvolva um algoritmo para a solução desse problema.

**Atividade**  

Um homem precisa atravessar um rio com um barco que possui capacidade de transportar apenas ele mesmo e mais uma de suas três cargas, que são: um lobo, um bode e uma caixa de alfafa. Indique as ações necessárias para que o homem consiga atravessar o rio sem perder suas cargas. Algumas regras devem ser sempre respeitadas: o lobo não pode ficar sozinho com o bode, o bode não pode ficar sozinho com a alfafa. 

- Utilize apenas a função `atravessar(p)`
    - p, é o passageiro ou carga do barco, que podem ser `lobo`, `bode`, `alfafa` ou `ninguém`;
    - a função `atravessar` vai de um lado a outro, partindo do lado em que o barco está.

