---
title: "Expressões : Exercícios"
subtitle: "Algoritmos e Estruturas de Dados"
author: "Prof. Darlon Vasata"
bibliography: references.bib
csl: abnt.csl

format:
  revealjs:
    smaller: true

  beamer:
    fontsize: "8pt"
---

- Faça um programa que pergunta um número ao usuário, e em seguida mostra o antecessor e o sucessor desse número.  

<details>
<summary>Resposta</summary>

::: {.content-visible when-profile="pseudocodigo"}

```c
inicio;
//variaveis
inteiro valor;
inteiro antecessor, sucessor;

//entrada
escreva("Digite um número: ");
leia(valor);

//processamento
antecessor = valor -1;
sucessor   = valor +1

//saida
escreva("O antecessor de ", valor, " é: ", antecessor);
escreva("O sucessor de ", valor, " é:", sucessor);

fim;
```
:::

::: {.content-visible when-profile="java"}

```c
//Variáveis
int valor;
int antecessor, sucessor;
Scanner entrada;

//Entrada
System.out.println("Digite um número: ");
entrada = new Scanner(System.in);
valor = entrada.nextInt();
entrada.close();

//Processamento
antecessor = valor -1;
sucessor = valor +1;

//Saída
System.out.println("O antecessor de " + valor + " é " + antecessor);
System.out.println("O sucessor de "   + valor + " é " + sucessor);
```

:::

::: {.content-visible when-profile="python"}

```python
#Entrada
print('Digite um número')
valor = input()
valor = int(valor)

#Processamento
antecessor = valor -1
sucessor = valor +1

#Saída
print(f'O antecessor de {valor} é {antecessor}', )
print(f'O sucessor de {valor} é {sucessor}', )
```


:::

</details>


---

1. Faça um programa que pergunta o nome do usuário, e em seguida mostra a frase "Boa tarde" seguida do nome do usuário.  

---

2. Pergunte um número ao usuário, e mostre o valor desse número ao cubo.

---

3. Pergunte três valores ao usuário, que correspondem às horas, minutos e segundos do horário atual. Calcule quantos segundos se passaram desde 00:00 horas.  
(Adaptado de @menezes2019, pg. 72)

---

4. Pergunte um número ao usuário, e em seguida mostre a raiz quadrada e a raiz cúbica desse número.

---

5. Escreva um programa que pergunte a quantidade de km percorridos por um carro alugado pelo usuário, assim como a quantidade de dias pelos quais o carro foi alugado. Calcule o preço a pagar, sabendo que o carro custa R\$ 60,00 por dia e R\$ 0,15 por km rodado.  

(Fonte: [@menezes2019], pg. 72)

---

6. Escreva um programa para ler as dimensões de um retângulo, com o tamanho da base ($b$) e da altura ($h$). Calcule o mostre o perímetro ($p$) e área ($a$) desse retângulo.  

$$
p = 2(b+h)
a = bh
$$  


---

7. Pergunte ao usuário o valor do raio ($r$) de um círculo, e em seguida mostre o perímetro ($p$) e a área ($a$) desse círculo.
$$
p = 2\pi r
a = \pi r^2
$$

---

8. Faça  um  algoritmo  que  leia  três  notas ($N_1$, $N_2$ e $N_3$)  de  um  aluno,  calcule  e  escreva  a  média  final  deste  aluno. Considerar que a média ($M$) é ponderada e que o peso das notas é 2, 3 e 5. A equação para o cálculo da média final é: 
$$
M = \frac{N_1 \times 2 + N_2 \times 3 + N_3 \times 5}{2+3+5}
$$  
(Fonte: [@carvalho2007])

---

9. Faça um programa que solicite o preço de uma mercadoria e o percentual de desconto. Exiba o valor do desconto e o preço a pagar.  
(Fonte: [@menezes2019], pg. 72)

---

10. Faça um programa que calcule o aumento de um salário. Ele deve solicitar o valor do salário e a porcentagem de aumento. Exiba o valor do aumento e do novo salário.  
(Fonte: [@menezes2019], pg. 72)

---

11. Peça ao usuário que informe o valor de um boleto, o percentual de juros cobrado e o número de dias em atraso. O programa deve calcular o valor total a ser pago, utilizando a fórmula  
$$
Total = Valor + Valor \times \frac{Juros}{100} \times Dias
$$  
(Adaptado de [@lopes2011])

---

12. Considere que houve uma eleição, na qual três candidatos concorreram ($C_a$, $C_b$ e $C_c$). O usuário deve informar quantos votos cada candidato recebeu e quantidade de votos brancos e nulos. O programa deve calcular e mostrar a quantidade total de eleitores, o percentual de votos que cada candidato recebeu, o percentual de votos brancos e o percentual de votos nulos. O cálculo dos percentuais é dado em relação ao total de votos da eleição.  
(Adaptado de LOPES, 2011)

---

13. O  custo  de  um  carro  novo  ao  consumidor  é  a  soma  do  custo  de  fábrica  com a  porcentagem  do distribuidor e dos impostos (aplicados ao custo de fábrica). Supondo que o percentual do distribuidor seja  de  28%  e  os  impostos  de  45%,  desenvolva  um  algoritmo que receba como entrada o valor do custo  de  fábrica  de  um  carro, e partir de disso calcule e mostre o custo final do carro ao consumidor.  
(Adaptado de CARVALHO, 2007)

---

14. Uma revendedora de carros usados paga a seus funcionários vendedores um salário fixo por mês, mais  uma  comissão  fixa  de 5% sobre o valor de todos os carros vendidos pelo funcionário. Escreva um algoritmo que receba como entrada o valor total de suas vendas e seu salário fixo, e em seguida calcula e apresenta o salário final do vendedor.  
(Adaptado de [@carvalho2007]).

---

15. Suponha que `A`, `B` e `C` são variáveis de tipo inteiro, com valores iguais a $5$, $10$ e $-8$, respectivamente, e uma variável real `D`, com valor de $1.5$. Quais serão os resultados das expressões aritméticas a seguir?  

::: {.content-visible when-profile="pseudocodigo"}

`2 * A % 3 - C`  
`(sqrt(-2 * C) / 4)`  
`((20 / 3) / 3) + pow(2, 8) / 2`  
`(30 % 4 * pow(3, 3)) * (-1)`  
`pow(-C, 2) + (D * 10) / A`  
`sqrt(pow(A, B/A)) + C * D`  

:::

::: {.content-visible when-profile="java"}

`2 * A % 3 - C`  
`Math.sqrt(-2 * C) / 4`  
`((20 / 3) / 3) + Math.pow(2, 8) / 2`  
`(30 % 4 * Math.pow(3, 3)) * (-1)`  
`Math.pow(-C, 2) + (D * 10) / A`  
`Math.sqrt(Math.pow(A, B/A)) + C * D`  

:::

::: {.content-visible when-profile="python"}

`2 * A % 3 - C`  
`sqrt(-2 * C) / 4`  
`((20 / 3) / 3) + 2**8 / 2`  
`(30 % 4 * 3**3) * (-1)`  
`-C**2 + (D * 10) / A`  
`sqrt(A**(B/A)) + C * D`  


:::

::: {.content-visible when-profile="c"}

`2 * A % 3 - C`  
`sqrt(-2 * C) / 4`  
`((20.0 / 3) / 3) + 2**8 / 2`  
`(30 % 4 * 3**3) * (-1)`  
`pow(-C, 2) + (d * 10) / A`  
`sqrt(pow(A, B / A)) + C * D`  

:::

---

16. Sendo P, Q e R variáveis de tipo inteiro, com valores iguais a 2, 3 e 12, respectivamente, e
uma variável real S, com valor de 4.5, quais os valores fornecidos por cada uma das expressões
aritméticas abaixo?

::: {.content-visible when-profile="pseudocodigo"}


`((100 * Q) / P + R)`  
`S % (P - 1) - Q * R`  
`(P * R) % 5 - Q / 2`  
`1 + rad( pot(P, 3) + 3 * R + 5)`  
`1 + ((R + P) / pot (Q, 2))`  
`rad(rad(16)) * pot(2, 3)` 

:::

::: {.content-visible when-profile="java"}

`((100 * Q) / P + R)`  
`S % (P - 1) - Q * R`  
`(P * R) % 5 - Q / 2`  
`1 + Math.sqrt( Math.pow(P, 3) + 3 * R + 5)`  
`1 + (int)((R + P) / Math.pow (Q, 2))`  
`Math.sqrt(Math.sqrt(16)) * Math.pow(2, 3)` 

:::

::: {.content-visible when-profile="python"}

`((100 * Q) / P + R)`  
`S % (P - 1) - Q * R`  
`(P * R) % 5 - Q / 2`  
`1 + sqrt( P**3 + 3 * R + 5)`  
`1 + ((R + P) / Q**2)`  
`sqrt(sqrt(16)) * 2**3` 
:::

::: {.content-visible when-profile="c"}

`((100 * Q) / P + R)`  
`S % (P - 1) - Q * R`  
`(P * R) % 5 - Q / 2`  
`1 + sqrt( pow(P, 3) + 3 * R + 5)`  
`1 + ((R + P) / pow (Q, 2))`  
`sqrt(sqrt(16)) * pow(2, 3)`  

:::

---

17. Considere as seguintes atribuições, R = 2, S = 5, T = -1, X = - 3, Y = -1 e Z = 0, resolver as
expressões abaixo:

::: {.content-visible when-profile="pseudocodigo"}

### Pseudocódigo

`(R >=5) ou (T > Z) e (X - Y + R > 3 * Z)`  
`(T + 3 >= 4) e !(3 * R/2 < S * 3)`  
`(X == 2) ou (Y = 1) e ((Z == 0) ou (R > 3) e (S < 10))`  
`(R != S) ou !(sqrt(R) < sqrt(X)) e (8327 * X * S * Z == 0)` 

:::

::: {.content-visible when-profile="java"}

`(R >=5) || (T > Z) && (X - Y + R > 3 * Z)`  
`(T + 3 >= 4) && !(3 * R/2 < S * 3)`  
`(X == 2) || (Y == 1) && ((Z == 0) || (R > 3) && (S < 10))`  
`(R != S) || !(Math.sqrt(R) < Math.sqrt(X)) && (8327 * X * S * Z == 0)` 

:::

::: {.content-visible when-profile="python"}

`(R >=5) or (T > Z) and (X - Y + R > 3 * Z)`  
`(T + 3 >= 4) and not(3 * R/2 < S * 3)`  
`(X == 2) or (Y == 1) and ((Z == 0) or (R > 3) and (S < 10))`  
`(R != S) or not sqrt(R) < sqrt(X) and (8327 * X * S * Z == 0)`  

:::

::: {.content-visible when-profile="c"}

`(R >=5) || (T > Z) && (X - Y + R > 3 * Z)`  
`(T + 3 >= 4) && !(3 * R/2 < S * 3)`  
`(X == 2) || (Y = 1) && ((Z == 0) || (R > 3) && (S < 10))`  
`(R != S) || !(sqrt(R) < sqrt(X)) && (8327 * X * S * Z == 0)`  

:::

---

18. Resolva as expressões abaixo, apresentando o resultado final. Considere o valor de `PI` como $3,14$:


::: {.content-visible when-profile="pseudocodigo"}

`(18 / 3 / 2 - 1) * 5 - 4 - (2 + 3 + 5) / 2`  
`26.0 / 6.0 / 2.0`  
`7 % 4 - 8 / (3 + 1)`  
`(5 != 2) ou não(7 > 4) e (4 <= PI)`  
`((18 / 3) == 5) e sqrt(100) == 11`  
`(12 >= 5 * 2) e (4 * 5 > 24 / 6)`  
`(2 >= 5) e não(6 <= 2 * 3) ou (10 != 10)`  

:::

::: {.content-visible when-profile="java"}

`(18 / 3 / 2 - 1) * 5 - 4 - (2 + 3 + 5) / 2`  
`26.0 / 6.0 / 2.0`  
`7 % 4 - 8 / (3 + 1)`  
`(5 != 2) || !(7 > 4) && (4 <= PI)`  
`((18 / 3) == 5) && Math.sqrt(100) == 11`  
`(12 >= 5 * 2) && (4 * 5 > 24 / 6)`  
`(2 >= 5) && !(6 <= 2 * 3) || (10 != 10)`  

:::

::: {.content-visible when-profile="python"}

`(18 / 3 / 2 - 1) * 5 - 4 - (2 + 3 + 5) / 2`  
`26.0 / 6.0 / 2.0`  
`7 % 4 - 8 / (3 + 1)`  
`(5 != 2) or not(7 > 4) and (4 <= PI)`  
`((18 / 3) == 5) and sqrt(100) == 11`  
`(12 >= 5 * 2) and (4 * 5 > 24 / 6)`  
`(2 >= 5) and not(6 <= 2 * 3) or (10 != 10)`   

:::

::: {.content-visible when-profile="c"}

`(18 / 3 / 2 - 1) * 5 - 4 - (2 + 3 + 5) / 2`  
`26.0 / 6.0 / 2.0`  
`7 % 4 - 8 / (3 + 1)`  
`(5 != 2) || !(7 > 4) && (4 <= PI)`  
`((18 / 3) == 5) && sqrt(100) == 11`  
`(12 >= 5 * 2) && (4 * 5 > 24 / 6)`  
`(2 >= 5) && !(6 <= 2 * 3) || (10 != 10)`  

:::

---

19. Resolva as expressões a seguir, quanto a seu valor lógico.

::: {.content-visible when-profile="pseudocodigo"}

`2 * 4 == 24 / 3`  
`15 % 4 < 19 % 6`  
`3 * 5 <= pot(3, 2) / 0.5`  
`2 + 8 % 7 >= 3 * 6 - 15`  

:::

::: {.content-visible when-profile="java"}

`2 * 4 == 24 / 3`  
`15 % 4 < 19 % 6`  
`3 * 5 <= Math.pow(3, 2) / 0.5`  
`2 + 8 % 7 >= 3 * 6 - 15`   

:::

::: {.content-visible when-profile="python"}

`2 * 4 == 24 / 3`  
`15 % 4 < 19 % 6`  
`3 * 5 <= 3**2 / 0.5`  
`2 + 8 % 7 >= 3 * 6 - 15`   

:::

::: {.content-visible when-profile="c"}

`2 * 4 == 24 / 3`  
`15 % 4 < 19 % 6`  
`3 * 5 <= pow(3, 2) / 0.5`  
`2 + 8 % 7 >= 3 * 6 - 15`  

:::

---

20. Resolva as expressões a seguir, quanto a seu valor lógico.

::: {.content-visible when-profile="pseudocodigo"}

`2 < 5 ou 15 / 3 == 5`  
`falso ou 20 / (18 / 3) != (21 / 3) / 2`  

:::

::: {.content-visible when-profile="java"}

`2 < 5 || 15 / 3 == 5`  
`false || 20.0 / (18.0 / 3) != (21.0 / 3) / 2`  

:::

::: {.content-visible when-profile="python"}

`2 < 5 or 15 / 3 == 5`  
`False or 20 / (18 / 3) != (21 / 3) / 2`   

:::

::: {.content-visible when-profile="c"}

`2 < 5 || 15 / 3 == 5`  
`0 || 20.0 / (18.0 / 3) != (21.0 / 3) / 2`  

:::

---

21. Considerando as variáveis numéricas X, Y e Z, contendo os valores 2, 5 e 9, respectivamente, a
variável literal NOME, contendo o literal "MARIA"; e a variável lógica SIM, contendo o valor
lógico Verdadeiro (V), observar os resultados obtidos das expressões lógicas a seguir.

::: {.content-visible when-profile="pseudocodigo"}

`X + Y > Z e NOME=="MARIA"`  
`SIM e Y >= X`  
`não SIM e Z / Y + 1 == X`  
`NOME=="JORGE" e SIM ou X**2 < Z + 10`  

:::

::: {.content-visible when-profile="java"}

`X + Y > Z && NOME=="MARIA"`  
`SIM || Y >= X`  
`!SIM && Z / Y + 1 == X`  
`NOME=="JORGE" && SIM || Math.pow(X, 2) < Z + 10` 

:::

::: {.content-visible when-profile="python"}

`X + Y > Z and NOME=="MARIA"`  
`SIM or Y >= X`  
`not SIM and Z / Y + 1 == X`  
`NOME=="JORGE" and SIM or X**2 < Z + 10`  

:::

::: {.content-visible when-profile="c"}

`X + Y > Z && strcmp(NOME,"MARIA")`  
`SIM || Y >= X`  
`!SIM && (int) Z / Y + 1 == X`  
`strcmp(NOME,"JORGE") && SIM || pow(X, 2) < Z + 10`  

:::

---

22. Considerando A e C variáveis inteiras, contendo os valores, 1 e 8 e, B como uma variável real, com
o valor 4.5; e TESTE variável lógica contendo o valor verdadeiro (V), determinar os resultados
obtidos da avaliação das seguintes expressões:

::: {.content-visible when-profile="pseudocodigo"}

`A == 1 e TESTE`  
`A + C == rad(81) ou TESTE != falso`  
`não TESTE ou C % 2 == 0.5`  
`C < 10 ou TESTE`  
`TESTE e não TESTE`  
`pot(A, 2) + rad(A + C) == 3 e (A + B > 13)` 

:::

::: {.content-visible when-profile="java"}

`A == 1 && TESTE`  
`A + C == Math.sqrt(81) || TESTE != false`  
`!TESTE || C % 2 == 0.5`  
`C < 10 || TESTE`  
`TESTE && !TESTE`  
`Math.pow(A, 2) + Math.sqrt(A + C) == 3 && (A + B > 13)`  

:::

::: {.content-visible when-profile="python"}

`A == 1 and TESTE`  
`A + C == sqrt(81) or TESTE != False`  
`not TESTE or C % 2 == 0.5`  
`C < 10 or TESTE`  
`TESTE and not TESTE`  
`pow(A, 2) + sqrt(A + C) == 3 and (A + B > 13)`  

:::

::: {.content-visible when-profile="c"}

`A == 1 && TESTE`  
`A + C == sqrt(81) || TESTE != 0`  
`!TESTE || C % 2 == 0.5`  
`C < 10 || TESTE`  
`TESTE && !TESTE`  
`pow(A, 2) + sqrt(A + C) == 3 && (A + B > 13)`  

:::

---

23. Determine os resultados na avaliação das expressões lógicas seguintes, sabendo que A, B, C
contêm, respectivamente, 2, 7, 3.5, e que existe uma variável lógica L cujo valor é F.


::: {.content-visible when-profile="pseudocodigo"}

`B == A * C e (L or verdadeiro)`  
`B > A ou B == pot(A, A)`  
`L e B / A >= C ou não(A <=C)`  
`não L ou verdadeiro e rad(A + B) >= C`  
`B / A == C ou B / A != C`  
`L ou pot(B, A) <= C * 10 + A * B`  
`não verdadeiro ou pot(3, 2) / 3 < 15 - 35 % 7`  
`não (5 != 10 / 2) or 1 e 2 - 5 > 5 - 2 ou verdadeiro`  
`pot(2, 4) != 4 + 2 or 2 + 3 * 5 / 3 % 5 > 0`

:::

::: {.content-visible when-profile="java"}

`B == A * C && (L || true)`  
`B > A || B == Math.pow(A, A)`  
`L && (int) B / A >= C || !(A <=C)`  
`!L || true && Math.sqrt(A + B) >= C`  
`B / A == C || B / A != C`  
`L || Math.pow(B, A) <= C * 10 + A * B`  
`!true || Math.pow(3, 2) / 3 < 15 - 35 % 7`  
`!(5 != 10 / 2) || true && 2 - 5 > 5 - 2 || true`  
`Math.pow(2, 4) != 4 + 2 || 2 + 3 * 5 / 3 % 5 > 0` 

:::

::: {.content-visible when-profile="python"}

`B == A * C and (L or True)`  
`B > A or B == pow(A, A)`  
`L and B / A >= C or not(A <=C)`  
`not L or True and sqrt(A + B) >= C`  
`B / A == C or B / A != C`  
`L or pow(B, A) <= C * 10 + A * B`  
`not True or pow(3, 2) / 3 < 15 - 35 % 7`  
`not (5 != 10 / 2) or True and 2 - 5 > 5 - 2 or True`  
`pow(2, 4) != 4 + 2 or 2 + 3 * 5 / 3 % 5 > 0` 

:::

::: {.content-visible when-profile="c"}

`B == A * C && (L || true)`  
`B > A || B == pow(A, A)`  
`L && (int) B / A >= C || !(A <=C)`  
`!L || true && sqrt(A + B) >= C`  
`B / A == C || B / A != C`  
`L || pow(B, A) <= C * 10 + A * B`  
`!true || pow(3, 2) / 3 < 15 - 35 % 7`  
`!(5 != 10 / 2) || true && 2 - 5 > 5 - 2 || true`  
`pow(2, 4) != 4 + 2 || 2 + 3 * 5 / 3 % 5 > 0`  

:::

---

24. Sabendo que A = 5, B = 4, C = 3 e D = 6, informe se as expressões abaixo são verdadeiras ou
falsas.


::: {.content-visible when-profile="pseudocodigo"}

`(A > C) e (C <= D)`  
`(A + B) > 10 ou (A + B) == (C + D)`  
`(A - C) == 0 ou não (D >= 99) e (B + 2) == 6`  
`(A >= C) e (B >= C)` 

:::

::: {.content-visible when-profile="java"}

`(A > C) && (C <= D)`  
`(A + B) > 10 || (A + B) == (C + D)`  
`(A - C) == 0 || !(D >= 99) && (B + 2) == 6`  
`(A >= C) && (B >= C)` 

:::

::: {.content-visible when-profile="python"}

`(A > C) and (C <= D)`  
`(A + B) > 10 or (A + B) == (C + D)`  
`(A - C) == 0 or not (D >= 99) and (B + 2) == 6`  
`(A >= C) and (B >= C)`  

:::

::: {.content-visible when-profile="c"}

`(A > C) && (C <= D)`  
`(A + B) > 10 || (A + B) == (C + D))`  
`(A - C) == 0 || !(D >= 99) && (B + 2) == 6)`  
`(A >= C) && (B >= C))`  

:::

---

25. Sabendo que A = 3, B = 7 e C = 4, informe se as expressões abaixo são verdadeiras ou falsas.

::: {.content-visible when-profile="pseudocodigo"}

`(A + C) > B`  
`B >= (A + 2)`  
`C == (B - A)`  
`(B + A) <= C`  
`(C + A) > B`  

:::

::: {.content-visible when-profile="java"}

`(A + C) > B`  
`B >= (A + 2)`  
`C == (B - A)`  
`(B + A) <= C`  
`(C + A) > B`  

:::

::: {.content-visible when-profile="python"}

`(A + C) > B`  
`B >= (A + 2)`  
`C == (B - A)`  
`(B + A) <= C`  
`(C + A) > B`  

:::

::: {.content-visible when-profile="c"}

`(A + C) > B`  
`B >= (A + 2)`  
`C == (B - A)`  
`(B + A) <= C`  
`(C + A) > B`  

:::

---

# Desafios

---

1. Desenvolva um algoritmo que recebe como entrada informações da hora e minuto inicial e final da partida de um determinado jogo. Com esses dados, informe a duração total do jogo, em horas e minutos (Obs: Para simplificação do problema, você pode considerar que o jogo sempre começa e termina no mesmo dia).

---

2. Desenvolva um algoritmo que recebe como entrada informações da hora e minuto inicial e final da partida de um determinado jogo. Com esses dados, informe a duração total do jogo, em horas e minutos. Considere que a duração de uma partida nunca será maior ou igual que 24 horas.

---

## Exercícios externos

---

### Beecrowd
1. [Beecrowd 1003 - Soma Simples](https://www.beecrowd.com.br/judge/pt/problems/view/1003)
1. [Beecrowd 1004 - Produto Simples](https://www.beecrowd.com.br/judge/pt/problems/view/1004)
1. [Beecrowd 1007 - Diferença](https://www.beecrowd.com.br/judge/pt/problems/view/1007)
1. [Beecrowd 3055 - Nota Esquecida ](https://www.beecrowd.com.br/judge/pt/problems/view/3055)
1. [Beecrowd 2786 - Piso da Escola ](https://www.beecrowd.com.br/judge/pt/problems/view/2786)
1. [Beecrowd 1021 - Notas e Moedas ](https://www.beecrowd.com.br/judge/pt/problems/view/1021)

## Referências

::: {#refs}
:::




---
