---
title: "Estruturas de controle"
subtitle: "Algoritmos e Estruturas de Dados"
author: "Prof. Darlon Vasata"
bibliography: references.bib
csl: abnt.csl

format:
  revealjs:
    smaller: true

  beamer:
    fontsize: "8pt"
    theme: Antibes
    #Themes: Warsaw CambridgeUS Antibes
---

# Estruturas de controle

::: {.content-visible when-profile="slides"}

---

:::

No desenvolvimento de algorimos, sempre planejamos as ações seguindos os conceitos de **entrada**, **processamento** e **saída**. Já sabemos que podemos elaborar os algoritmos com o uso de variáveis, funções e expressões [@forbellone2022, p. 45].

::: {.content-visible when-profile="slides"}

---

:::

Até agora, elaboramos nossos algorimos de forma que todas as instruções presentes no algoritmo são executadas: linha por linha e uma única vez.

::: {.content-visible when-profile="slides"}

---

:::

É necessário que possamos desenvolver algoritmos que possuam uma melhor capacidade de resolução de problemas. Para várias situações é necessário que determinadas partes do algoritmo sejam executadas e determinadas partes não. Ou até mesmo, que algumas partes sejam executadas mais do que uma vez.  

As estruturas que definem qual trecho será ou não executado, ou se será executado várias vezes, são definidas como **estruturas de controle**. Destas, as principais são estruturas de **seleção** e de **repetição**.

::: {.content-visible when-profile="slides"}

---

:::


## Referências

::: {#refs}
:::

